# Generated by Django 4.0.1 on 2022-12-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_categoryadmin_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='News', max_length=255),
        ),
        migrations.DeleteModel(
            name='CategoryAdmin',
        ),
    ]
